### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cstewart90** [H4jen/h4jen_minqlx#1]
This project should be licensed under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) as it is derivative work of [minqlx](https://github.com/MinoMino/minqlx/) which itself is [licensed](https://github.com/MinoMino/minqlx/blob/master/LICENSE) under GPLv3. More information about how open source licenses work [here](http://openacs.org/about/licensing/open-source-licensing). Note: I am not a lawyer or expert on open source licenses so I may be wrong.
Also what is this project? :confused: Were you just experimenting with different stuff for fun or is there some purpose to this madness. :see_no_evil:

**Comment by H4jen** [comment]
This is just for fun. don't bother.
